--- magma-2.2.0/example/Makefile	2016-11-20 17:20:02.000000000 -0800
+++ patch-files/Makefile	2017-07-03 15:58:13.541368989 -0700
@@ -6,16 +6,11 @@
 # Paths where MAGMA, CUDA, and OpenBLAS are installed.
 # MAGMADIR can be .. to test without installing.
 #MAGMADIR     ?= ..
-MAGMADIR     ?= /usr/local/magma
-CUDADIR      ?= /usr/local/cuda
-OPENBLASDIR  ?= /usr/local/openblas
-
-CC            = gcc
-FORT          = gfortran
-LD            = gcc
-CFLAGS        = -Wall
+MAGMADIR =   MAGMAROOT
+CUDADIR  =   $(CUDAHOME)
+
 # needs -fopenmp if MAGMA was compiled with OpenMP
-LDFLAGS       = -Wall #-fopenmp
+CFLAGS       = OPENMPFLAG
 
 
 # ----------------------------------------
@@ -31,7 +26,7 @@
 # may be lib instead of lib64 on some systems
 MAGMA_LIBS       := -L$(MAGMADIR)/lib -lmagma_sparse -lmagma \
                     -L$(CUDADIR)/lib64 -lcublas -lcudart -lcusparse \
-                    -L$(OPENBLASDIR)/lib -lopenblas
+                    -L$(MKLROOT)/lib/intel64  -lmkl_COMPILERTYPE_lp64 -lmkl_COMPILERNAME_thread -lmkl_core INTELCOMPILERFLAGS -lpthread -lstdc++ -lm
 
 
 # ----------------------------------------
@@ -70,23 +65,23 @@
 	$(CC) $(CFLAGS) $(MAGMA_CFLAGS) -c -o $@ $<
 
 example_v1: example_v1.o
-	$(LD) $(LDFLAGS) -o $@ $^ $(MAGMA_LIBS)
+	$(CC) $(LDFLAGS) -o $@ $^ $(MAGMA_LIBS)
 
 example_v2: example_v2.o
-	$(LD) $(LDFLAGS) -o $@ $^ $(MAGMA_LIBS)
+	$(CC) $(LDFLAGS) -o $@ $^ $(MAGMA_LIBS)
 
 example_sparse: example_sparse.o
-	$(LD) $(LDFLAGS) -o $@ $^ $(MAGMA_LIBS)
+	$(CC) $(LDFLAGS) -o $@ $^ $(MAGMA_LIBS)
 
 
 # ----------------------------------------
 # Fortran example
 # this uses capital .F90 to preprocess to define magma_devptr_t
 %.o: %.F90
-	$(FORT) $(F90FLAGS) $(MAGMA_F90FLAGS) -c -o $@ $<
+	$(FC) $(F90FLAGS) $(MAGMA_F90FLAGS) -c -o $@ $<
 
 fortran.o: $(CUDADIR)/src/fortran.c
 	$(CC) $(CFLAGS) $(MAGMA_CFLAGS) -DCUBLAS_GFORTRAN -c -o $@ $<
 
 example_f: example_f.o fortran.o
-	$(FORT) $(LDFLAGS) -o $@ $^ $(MAGMA_LIBS)
+	$(FC) $(LDFLAGS) -o $@ $^ $(MAGMA_LIBS)
